;:set syn=dosini

[global/wm]
#margin-top = 8
#margin-bottom = 8
#margin-left = 8
#margin-right = 8


[colors]
;orange = #FF6200
;orange = #d65d0e
darkgray = ${xrdb:color8}
orange = ${xrdb:color9}
white = #ebdbb2
gray = #585858
black = #090909
red = #c795ae
blue = #95aec7
yellow = #c7ae95
green = #aec795
#background = #1f222d
background = #262626
background-alt = #4e4e4e
#foreground = #dfdfdf
foreground = ${xrdb:foreground}
foreground-alt = #4e4e4e
primary = #1f222d
secondary = #FF6200
alert = #fb4934

[bar/bar]
monitor = eDP
bottom = true
wm-restack = cwm
width = 1910
height = 26
offset-x = 5
offset-y = 5
radius = 5.0
border-size = 1

modules-right = separator volume separator date

; background = ${colors.background}
; foreground = ${colors.foreground}

underline-size = 0
underline-color = ${colors.white}

tray-detached = false
tray-position =
tray-offset-x = 0
tray-offset-y = 0
;tray-maxsize = 16
tray-padding = 0
tray-transparent = false
tray-scale = 1.0

; font-0 = "monospace:size=8;2"
; font-1 = "FontAwesome:size=8;2"

[module/date]
type = internal/date
#date-alt =   %A %H:%M
date = %{F#928374}%{F-} %H:%M
interval = 5
format-underline = ${colors.white}
;format-background = ${colors.black}
format-foreground = ${colors.foreground}
format-padding = 2

label-separator = |

[module/volume]
type = internal/volume

format-volume = <label-volume>
format-volume-padding = 2

format-volume-underline = ${colors.white}

label-volume = %{F#928374} %{F-}%percentage:3%%
#label-volume-foreground = ${color.white}

label-muted =%{F#928374} %{F-}mute
format-muted = <label-muted>
format-muted-underline = ${colors.white}
format-muted-padding = 2
#label-muted-foreground = ${colors.gray}

format-padding = 2

[module/separator]
type = custom/text
content = |
content-foreground = #4e4e4e
